### ISSUE TITLE
Unable to View the Freshdesk Widget

### ISSUE THREAD

**Issue by itsgaurav** [taz77/drupal_freshdesk#1]
Hey Brady,

I tried installing this module into drupal and I can see the admin configuration page asking for freshdesk url, api key, etc.  but I am having trouble finding the widget when I login to drupal as a authenticated user.
Could you please write the steps explaining where is the widget displayed.

Thanks,

**Comment by taz77** [comment]
Hello,

Please read the README it explains how to go about displaying the widget on your site. The widget is inserted via Token in Drupal core. There are other contrib modules you may choose to use in order to show the widget or craft your own solution. 

Regards,
Brady
